### ISSUE TITLE
Trouble parsing attribute without quotes

### ISSUE THREAD

**Issue by AwaisBinKaleem** [journeyapps/domparser.js#32]
i want to parse external xml getting from backend that is without quotes but having Trouble parsing attribute without quotes.
example:
`<div width=50% height=50vh> content </div>.`

plz add this feature to DOMParser()

**Comment by rkistner** [comment]
This library only supports parsing XML, not HTML, so that is unfortunately outside the scope of the project.

**Comment by AwaisBinKaleem** [comment]
> This library only supports parsing XML, not HTML, so that is unfortunately outside the scope of the project.

so which package should be used to parse HTML?
and can this feature be added in this liberary?

**Comment by rkistner** [comment]
It cannot be added as a feature to this library. Parsing attributes without quotes is just one of many differences between XML and HTML, and it would make the parsing a lot more complicated. This library is based on https://github.com/isaacs/sax-js, which also does not support HTML.

I do not have any suggestions for other libraries - it depends a lot on your specific use case. For example, in a browser the simplest is to use the built-in DOMParser, if you don't need line/column info. For NodeJS, there should be many other options.
